// Code generated by "stringer -type=MouseButton"; DO NOT EDIT.

package termesc

import "fmt"

const _MouseButton_name = "NoButtonLeftButtonMiddleButtonRightButtonReleaseButtonScrollUpButtonScrollDownButton"

var _MouseButton_index = [...]uint8{0, 8, 18, 30, 41, 54, 68, 84}

func (i MouseButton) String() string {
	if i < 0 || i >= MouseButton(len(_MouseButton_index)-1) {
		return fmt.Sprintf("MouseButton(%d)", i)
	}
	return _MouseButton_name[_MouseButton_index[i]:_MouseButton_index[i+1]]
}
